New script

diff --git a/ternoa b/ternoa
--- a/ternoa
+++ b/ternoa
@@ -1,126 +1,215 @@
 #!/bin/bash
 
-TERNOA_VERSION="1.3.2"
-TERNOA_ENV="mainnet"
+###########################################
+# Ternoa Installer Script
+# Author: SOUFIANE BOUCHAARA
+# Email: contact@soufianebouchaara.com
+# Version: 1.2.0
+###########################################
 
-DOWNLOAD_URL="https://github.com/capsule-corp-ternoa/ternoa-node/releases/download/v${TERNOA_VERSION}/ternoa"
 
-_divider="--------------------------------------------------------------------------------"
-_prompt=">>>"
-_indent="   "
+# Function to display a spinner while waiting for a process to finish
+spinner() {
+  local pid=$1
+  local delay=0.15
+  local spinstr='|/-\'
 
-validator_name=""
-short_name=""
-port_number=0
+  echo -n "Installing Ternoa "
+  while ps -p $pid > /dev/null; do
+    for i in $(seq 0 3); do
+      echo -n "${spinstr:$i:1}"
+      echo -en "\b"
+      sleep $delay
+    done
+  done
+  echo -e "\bDone!"
+}
 
-cat 1>&2 <<EOF
-                                  Welcome to TERNOA installer 
+# Function to check if a service is running and stop it
+stop_service() {
+  local service_name=$1
+  if systemctl is-active --quiet $service_name; then
+    systemctl stop $service_name
+    echo "Stopping $service_name"
+  fi
+}
 
-$_divider
-This script fork from https://packages.ternoa.network/ternoa/installer
-Website: https://ternoa.com
-Docs: https://ternoa-2.gitbook.io/ternoa-testnet-guide/
-Support : https://ternoahelp.zendesk.com/hc/en-150
-$_divider
+# Stop ternoa service if running
+stop_service ternoa
 
-EOF
 
-echo "$_prompt We'll be installing Ternoa via a pre-built archive at ${DOWNLOAD_URL}/"
-
-# Check architecture
-if [ $(arch) != "x86_64" ]; then
-    echo "$_prompt This binary can only be run on x86 architecture."
-    echo "$_prompt Exiting..."
-    exit 1
+# Check if the script is run as root
+if [ "$EUID" -ne 0 ]; then
+  echo "Please run as root"
+  exit
 fi
 
-# Pre-requisites installation
-echo "$_prompt Installing pre-requisites..."
-sudo apt update
-sudo apt install build-essential git cmake protobuf-compiler -y
-echo "$_prompt Pre-requisites installed successfully."
+# Detect Debian/Ubuntu
+if [ -f /etc/debian_version ]; then
+  DISTRO="debian"
+elif [ -f /etc/lsb-release ]; then
+  DISTRO="ubuntu"
+else
+  echo "Unsupported distribution"
+  exit
+fi
 
-PS3='Please choose the ternoa chain environment: '
-select opt in Alphanet Mainnet
-do
-    case $opt in
-        Alphanet)
-            echo "Connecting to Alphanet ...";
-            TERNOA_ENV="alphanet"; break
-            ;;
-        Mainnet)
-            echo "Connecting to Mainnet ...";
-            TERNOA_ENV="mainnet";  break
-            ;;
-        *) 
-            echo "invalid option $REPLY"; 
-            exit 1 
-            ;;   
-    esac
+# Set installation variables
+# read -p "Enter Ternoa Version (default: v1.3.2): " VERSION
+VERSION=v1.3.2
+
+BINARY_URL="https://github.com/capsule-corp-ternoa/ternoa-node/releases/download/$VERSION/ternoa"
+INSTALL_PATH="/usr/bin/ternoa"
+USERNAME="ternoa"
+GROUPNAME="root"
+
+# Create a user and group for Ternoa service
+groupadd $GROUPNAME
+useradd -m -g $GROUPNAME $USERNAME
+usermod  -aG sudo $USERNAME
+
+# Download binary with spinner
+wget $BINARY_URL -O $INSTALL_PATH &
+spinner $!
+
+
+# Create the base path directory and grant write permissions to root group
+BASE_PATH="/block/chain/node-data"
+mkdir -p $BASE_PATH
+chown $USERNAME:$GROUPNAME $BASE_PATH
+chmod a+x $BASE_PATH
+
+# Get user inputs
+read -p "Node Name (required): " NODE_NAME
+if [ -z "$NODE_NAME" ]; then
+  echo "Node Name is required. Exiting."
+  exit 1
+fi
+
+# Input validation for Chain Name
+CHAIN_NAME=""
+while true; do
+  # read -p "Chain Name (alphanet/mainnet/betanet, default: mainnet): " CHAIN_NAME
+  CHAIN_NAME=mainnet
+  case $CHAIN_NAME in
+    alphanet|mainnet|betanet)
+      break
+      ;;
+    *)
+      echo "Invalid Chain Name. Please enter alphanet, mainnet, or betanet."
+      ;;
+  esac
 done
 
-while true; do
-    read -rp "Enter Your Validator (REAL) Name: " validator_name  </dev/tty
-    if [[ ! -z "$validator_name" ]] ; then
-        break ;
-    fi
-done
+#Construct Ternoa command
+TERNOA_COMMAND="/usr/bin/ternoa --name $NODE_NAME --chain $CHAIN_NAME --base-path $BASE_PATH --ws-max-connections 1000  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'"
 
-while true; do
-    read -rp "Enter Your Common (SHORT) Name (no space): " short_name  </dev/tty
-    if [[ ! -z "$short_name" ]] ; then
-        break ;
-    fi
-done
+# Prompt for Validator only if not specified in the command line
+if [ -z "$VALIDATOR" ]; then
+  # read -p "Validator (true/false, default: false): " USER_VALIDATOR
+  VALIDATOR=false
+fi
 
-while true; do
-    read -rp "Enter the port number: " port_number </dev/tty
+# read -p "Archive Mode (true/false, default: true): " ARCHIVE_MODE
+ARCHIVE_MODE=true
+# read -p "Enable Prometheus (true/false, default: false): " PROMETHEUS
+PROMETHEUS=true
 
-    # Check if the input is not empty and is a valid port number (in the range 1-65535)
-    if [[ ! -z "$port_number" ]] && [[ "$port_number" =~ ^[1-9][0-9]{0,4}$ && "$port_number" -ge 1 && "$port_number" -le 65535 ]]; then
-        break
+
+# Add --validator flag if the user specified true or enable RPC Calls
+if [ "$VALIDATOR" == "true" ]; then
+  TERNOA_COMMAND="$TERNOA_COMMAND --validator"
+else
+  TERNOA_COMMAND="$TERNOA_COMMAND --ws-external --rpc-external --rpc-cors all --rpc-methods=Safe "
+fi
+
+
+# Initialize PROMETHEUS_PORT with default value
+PROMETHEUS_PORT="9615"
+
+# Prompt for PROMETHEUS_PORT only if PROMETHEUS is true
+if [ "$PROMETHEUS" == "true" ]; then
+  while true; do
+    # read -p "Enter Prometheus Port (default: 9615, integer): " USER_PROMETHEUS_PORT
+    if [ -z "$USER_PROMETHEUS_PORT" ]; then
+      break
+    elif [[ ! "$USER_PROMETHEUS_PORT" =~ ^[0-9]+$ ]]; then
+      echo "Please enter a valid integer for Prometheus Port."
     else
-        echo "Invalid port number. Please enter a valid port number between 1 and 65535."
+      PROMETHEUS_PORT="$USER_PROMETHEUS_PORT"
+      break
     fi
-done
+  done
+fi
 
 
-# Download Ternoa binary
-sudo wget "$DOWNLOAD_URL" -O /usr/bin/ternoa
-sudo chmod +x "/usr/bin/ternoa"
+# Move ternoa binary to /usr/bin and make it executable for the root group
+mv $INSTALL_PATH /usr/bin/ternoa
+chown $USERNAME:$GROUPNAME /usr/bin/ternoa
+chmod a+x /usr/bin/ternoa
 
-# Create directory for Ternoa node data
-sudo mkdir -p "/opt/ternoa/node-data-${short_name}"
+
+
+# Add additional flags based on user inputs
+if [ "$PROMETHEUS" == "true" ]; then
+  TERNOA_COMMAND="$TERNOA_COMMAND --prometheus-port $PROMETHEUS_PORT"
+fi
+
+if [ "$ARCHIVE_MODE" == "false" ]; then
+  TERNOA_COMMAND="$TERNOA_COMMAND --database paritydb"
+else
+  TERNOA_COMMAND="$TERNOA_COMMAND --state-pruning archive"
+fi
+
+
 
 # Create systemd service file
-sudo tee /etc/systemd/system/ternoa-${short_name}.service > /dev/null <<EOT
+cat <<EOL > /etc/systemd/system/ternoa.service
 [Unit]
-Description=Ternoa Validator Node By Ternoa.com
+Description=Ternoa Node
 
 [Service]
-ExecStart=/usr/bin/ternoa --name "${validator_name}" --chain ${TERNOA_ENV} --base-path /opt/ternoa/node-data-${short_name} --ws-max-connections 1000 --prometheus-port 9615 --validator --telemetry-url "wss://telemetry.polkadot.io/submit/ 0" --state-pruning archive --port ${port_number}
-WorkingDirectory=/usr/bin
-KillSignal=SIGINT
-TimeoutStopSec=infinity
-User=root
-Restart=on-failure
-RestartSec=10s
-LimitNOFILE=10240
-SyslogIdentifier=ternoa-${short_name}
+ExecStart=$TERNOA_COMMAND
+Restart=always
+User=$USERNAME
+Group=$GROUPNAME
 
 [Install]
 WantedBy=multi-user.target
-EOT
+EOL
 
-# Reload systemd and start Ternoa service
-sudo systemctl daemon-reload
-sudo systemctl enable ternoa-${short_name}
-sudo systemctl start ternoa-${short_name}
+# Add ternoa user to sudoers
+echo "$USERNAME ALL=(ALL) ALL" | tee -a /etc/sudoers
 
-printf "%s Install succeeded!\n" "$_prompt"
-printf "\n"
-printf "%s You can restart ternoa service using : systemctl restart ternoa-${short_name}\n"
-printf "%s You can get the status of ternoa service using : systemctl status ternoa-${short_name}\n"
-printf "%s You can stop ternoa service using : systemctl stop ternoa-${short_name}\n"
-printf "\n"
-printf "%s More information at https://ternoa-2.gitbook.io/ternoa-testnet-guide/\n" "$_prompt"
+# Start and enable the service
+systemctl daemon-reload
+systemctl start ternoa
+systemctl enable ternoa
+
+echo "Running Ternoa with the following command :"
+echo "$TERNOA_COMMAND"
+echo "Ternoa installed successfully!"
+echo "Ternoa version: $VERSION"
+
+# Display journalctl logs for 10 seconds and kill the process
+echo "Displaying journalctl logs for 10 seconds..."
+journalctl -u ternoa --follow &
+JOURNAL_PID=$!
+
+# Wait for 10 seconds
+sleep 10
+
+# Kill the journalctl process
+kill $JOURNAL_PID
+
+echo "Logs displayed for 10 seconds. Exiting."
+
+
+# Check if ternoa service is running
+if systemctl is-active --quiet ternoa; then
+  echo "Ternoa installed successfully!"
+  echo "Ternoa version: $VERSION"
+  echo "Ternoa service is running."
+else
+  echo "Error: Ternoa service is not running."
+fi
